### PR TITLE
cloud-free setup for eval purposes

### PR DESCRIPTION
**Pull request by unreasonableman**
Let users curious about GRaaS run a server locally without the need for a google cloud account or project.

Steps:
- create a venv using `server/app-engine/requirements-cloudless.txt`
- activate venv
- run `python main.py -c <path-to-cert.pem> -k <path-to-key.pem>` # pem files constitute self-signed https cert

I ran the following tests for local cloudless server, local server and staging server:
- create and deploy bulk assignment
- run web app in bulk assignment mode and observer backfiling of trip IDs from assignment
- post-vehicle-positions
- post-service-alerts
- post-stop-time-entities

### CODE REVIEW

**Comment by owades** [comment]
@unreasonableman as a part of this PR I think it would make sense to also update docs - probably [new instance setup](https://github.com/cal-itp/graas/blob/main/docs/new-instance-setup.md)

**Review by owades — APPROVED** [review]
wow, elegant. see the comment i left about documentation

**Comment by unreasonableman** [comment]
@owades update docs per your suggestion. Requesting re-review, relevant commit is 05f32fd.

**Review by owades — APPROVED** [review]
nice, thanks!

**Pull request merged**
